server:
  port: 80

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#logging:
#  logback:
#    rollingpolicy:
#      max-history: 14
#  file:
#    name: ${user.dir}/logs/sample-assets-web/sample-assets-web.log
#  level:
#    net:
#      ib:
#        baraemjob: DEBUG